DROP TABLE T_IND_ANK
;

CREATE TABLE T_IND_ANK
(
INDANK_NO CHAR(14) NOT NULL,
INDSUM_NM VARCHAR(30),
INDSEX_CD CHAR(1),
INDBIR_DT CHAR(8) NOT NULL DEFAULT '18000101',
INDANK_ST CHAR(1) NOT NULL,
PYRASS_ST CHAR(1),
ENVASS_ST CHAR(1),
BDYCND_ASS_ST CHAR(1),
UPRASS_ST CHAR(1),
MEDASS_ST CHAR(1),
MEDREF_ST CHAR(1),
CON_ST CHAR(1),
OFCAPPR_ST CHAR(1),
ICMADM_ST CHAR(1),
LSTCHK_ST CHAR(1),
CCDCHK_ST CHAR(1),
CCDRCV_ST CHAR(1),
FLRCF_ST CHAR(1),
RERDRREF_ST CHAR(1) NOT NULL,
NFYREP_CD CHAR(1),
EXMREP_CD CHAR(1),
MEDEXM_REP_CD CHAR(1),
RNK_BDYCND CHAR(2),
RNK_ENV CHAR(2),
RNK_PYR CHAR(2),
RNK_UPR CHAR(2),
CNTCHG_NUM SMALLINT,
LNGTRMPND_FG CHAR(1),
ANKRTN_PRC CHAR(1),
NBS_OFIDSP_FG CHAR(1) NOT NULL,
INDANKMC_CD CHAR(1),
ANKCON_DT CHAR(8) NOT NULL DEFAULT '18000101',
INDANKCRT_CD CHAR(1) NOT NULL,
ICMADMCHK_FG CHAR(1) NOT NULL,
DEL_FG CHAR(1) NOT NULL,
ENT_DT TIMESTAMP NOT NULL,
ENTLOGIN_ID VARCHAR(20) NOT NULL,
ENTBSN_ID CHAR(13) NOT NULL,
UPD_DT TIMESTAMP NOT NULL,
UPDLOGIN_ID VARCHAR(20) NOT NULL,
UPDBSN_ID CHAR(13) NOT NULL,
UPDCNTR INTEGER NOT NULL,
LOCKUSR_ID VARCHAR(20),
LOCK_FG CHAR(1) NOT NULL DEFAULT '0',
LOCK_DT TIMESTAMP
)
;
COMMENT ON TABLE T_IND_ANK IS '被保険者案件情報';
 COMMENT ON COLUMN T_IND_ANK.INDANK_NO IS '被保険者案件番号';
 COMMENT ON COLUMN T_IND_ANK.INDSUM_NM IS '被保険者名寄せカナ';
 COMMENT ON COLUMN T_IND_ANK.INDSEX_CD IS '被保険者性別';
 COMMENT ON COLUMN T_IND_ANK.INDBIR_DT IS '被保険者生年月日';
 COMMENT ON COLUMN T_IND_ANK.INDANK_ST IS '被保険者案件ステータス';
 COMMENT ON COLUMN T_IND_ANK.PYRASS_ST IS '契約者査定ステータス';
 COMMENT ON COLUMN T_IND_ANK.ENVASS_ST IS '環境査定ステータス';
 COMMENT ON COLUMN T_IND_ANK.BDYCND_ASS_ST IS '体況査定ステータス';
 COMMENT ON COLUMN T_IND_ANK.UPRASS_ST IS '上位者査定ステータス';
 COMMENT ON COLUMN T_IND_ANK.MEDASS_ST IS '査定医査定ステータス';
 COMMENT ON COLUMN T_IND_ANK.MEDREF_ST IS '医事照会ステータス';
 COMMENT ON COLUMN T_IND_ANK.CON_ST IS '契約確認ステータス';
 COMMENT ON COLUMN T_IND_ANK.OFCAPPR_ST IS '役員決裁ステータス';
 COMMENT ON COLUMN T_IND_ANK.ICMADM_ST IS '不備管理ステータス';
 COMMENT ON COLUMN T_IND_ANK.LSTCHK_ST IS '最終チェックステータス';
 COMMENT ON COLUMN T_IND_ANK.CCDCHK_ST IS '成立チェックステータス';
 COMMENT ON COLUMN T_IND_ANK.CCDRCV_ST IS '成立後受付ステータス';
 COMMENT ON COLUMN T_IND_ANK.FLRCF_ST IS '不成立・クーリングオフステータス';
 COMMENT ON COLUMN T_IND_ANK.RERDRREF_ST IS '再保照会ステータス';
 COMMENT ON COLUMN T_IND_ANK.NFYREP_CD IS '告知書書類待ち';
 COMMENT ON COLUMN T_IND_ANK.EXMREP_CD IS '診査報状書類待ち';
 COMMENT ON COLUMN T_IND_ANK.MEDEXM_REP_CD IS '健康診断結果書類待ち';
 COMMENT ON COLUMN T_IND_ANK.RNK_BDYCND IS 'ランク(体況)';
 COMMENT ON COLUMN T_IND_ANK.RNK_ENV IS 'ランク(環境)';
 COMMENT ON COLUMN T_IND_ANK.RNK_PYR IS 'ランク(契約者)';
 COMMENT ON COLUMN T_IND_ANK.RNK_UPR IS 'ランク(上位者)';
 COMMENT ON COLUMN T_IND_ANK.CNTCHG_NUM IS '内容変更回数';
 COMMENT ON COLUMN T_IND_ANK.LNGTRMPND_FG IS '長期ペンディングフラグ';
 COMMENT ON COLUMN T_IND_ANK.ANKRTN_PRC IS '案件滞留工程';
 COMMENT ON COLUMN T_IND_ANK.NBS_OFIDSP_FG IS 'NBSR支社開示フラグ';
 COMMENT ON COLUMN T_IND_ANK.INDANKMC_CD IS '被保険者案件選択方法';
 COMMENT ON COLUMN T_IND_ANK.ANKCON_DT IS '案件契約日';
 COMMENT ON COLUMN T_IND_ANK.INDANKCRT_CD IS '被保険者案件生成区分';
 COMMENT ON COLUMN T_IND_ANK.ICMADMCHK_FG IS '不備管理チェック対象フラグ';
 COMMENT ON COLUMN T_IND_ANK.DEL_FG IS '削除フラグ';
 COMMENT ON COLUMN T_IND_ANK.ENT_DT IS '登録日時';
 COMMENT ON COLUMN T_IND_ANK.ENTLOGIN_ID IS '登録ログインID';
 COMMENT ON COLUMN T_IND_ANK.ENTBSN_ID IS '登録業務ID';
 COMMENT ON COLUMN T_IND_ANK.UPD_DT IS '更新日時';
 COMMENT ON COLUMN T_IND_ANK.UPDLOGIN_ID IS '更新ログインID';
 COMMENT ON COLUMN T_IND_ANK.UPDBSN_ID IS '更新業務ID';
 COMMENT ON COLUMN T_IND_ANK.UPDCNTR IS '更新カウンター';
 COMMENT ON COLUMN T_IND_ANK.LOCKUSR_ID IS 'ロックユーザーID';
 COMMENT ON COLUMN T_IND_ANK.LOCK_FG IS 'ロックフラグ';
 COMMENT ON COLUMN T_IND_ANK.LOCK_DT IS 'ロック日時';

;
ALTER TABLE T_IND_ANK
 ADD PRIMARY KEY (
INDANK_NO
)
;

DROP TABLE T_PYR_GRP
;

CREATE TABLE T_PYR_GRP
(
PYRGRP_NO CHAR(14) NOT NULL,
PYRSUM_NM VARCHAR(30),
PYRSEX_CD CHAR(1),
PYRBIR_DT CHAR(8) NOT NULL DEFAULT '18000101',
CON_YERTOT_PR BIGINT,
NOWSUB_PR_TOT BIGINT,
DEL_FG CHAR(1) NOT NULL,
ENT_DT TIMESTAMP NOT NULL,
ENTLOGIN_ID VARCHAR(20) NOT NULL,
ENTBSN_ID CHAR(13) NOT NULL,
UPD_DT TIMESTAMP NOT NULL,
UPDLOGIN_ID VARCHAR(20) NOT NULL,
UPDBSN_ID CHAR(13) NOT NULL,
UPDCNTR INTEGER NOT NULL,
LOCKUSR_ID VARCHAR(20),
LOCK_FG CHAR(1) NOT NULL DEFAULT '0',
LOCK_DT TIMESTAMP
)
;
COMMENT ON TABLE T_PYR_GRP IS '契約者紐付情報';
 COMMENT ON COLUMN T_PYR_GRP.PYRGRP_NO IS '契約者紐付番号';
 COMMENT ON COLUMN T_PYR_GRP.PYRSUM_NM IS '契約者名寄せカナ';
 COMMENT ON COLUMN T_PYR_GRP.PYRSEX_CD IS '契約者性別';
 COMMENT ON COLUMN T_PYR_GRP.PYRBIR_DT IS '契約者生年月日';
 COMMENT ON COLUMN T_PYR_GRP.CON_YERTOT_PR IS '既契約年換算保険料合計';
 COMMENT ON COLUMN T_PYR_GRP.NOWSUB_PR_TOT IS '今回申込保険料合計';
 COMMENT ON COLUMN T_PYR_GRP.DEL_FG IS '削除フラグ';
 COMMENT ON COLUMN T_PYR_GRP.ENT_DT IS '登録日時';
 COMMENT ON COLUMN T_PYR_GRP.ENTLOGIN_ID IS '登録ログインID';
 COMMENT ON COLUMN T_PYR_GRP.ENTBSN_ID IS '登録業務ID';
 COMMENT ON COLUMN T_PYR_GRP.UPD_DT IS '更新日時';
 COMMENT ON COLUMN T_PYR_GRP.UPDLOGIN_ID IS '更新ログインID';
 COMMENT ON COLUMN T_PYR_GRP.UPDBSN_ID IS '更新業務ID';
 COMMENT ON COLUMN T_PYR_GRP.UPDCNTR IS '更新カウンター';
 COMMENT ON COLUMN T_PYR_GRP.LOCKUSR_ID IS 'ロックユーザーID';
 COMMENT ON COLUMN T_PYR_GRP.LOCK_FG IS 'ロックフラグ';
 COMMENT ON COLUMN T_PYR_GRP.LOCK_DT IS 'ロック日時';

;
ALTER TABLE T_PYR_GRP
 ADD PRIMARY KEY (
PYRGRP_NO
)
;

;

