DROP TABLE IF EXISTS `tbl_UserMaster`;
CREATE TABLE `tbl_UserMaster` (
  `USERID` varchar(16) NOT NULL COMMENT 'ユーサーＩＤ',
  `USERNAME` varchar(20) NOT NULL COMMENT 'ユーザー名称',
  `PASSWORD` varchar(32) NOT NULL COMMENT 'パスワード',
  `USERPREVL` char(1) NOT NULL COMMENT 'ユーザー権限',
  `COMPANYFLG` char(1) NOT NULL COMMENT '社内フラグ',
  `MAILADDRESS` varchar(40) NOT NULL COMMENT 'メール',
  `CUSTOMERCODE` varchar(6) NOT NULL COMMENT '得意先コード',
  `DEPARTMENTID` varchar(4) NOT NULL COMMENT '部門ＩＤ',
  `CLASSID` varchar(4) DEFAULT NULL COMMENT '課ＩＤ',
  PRIMARY KEY (`USERID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='ユーサーマスター';

DROP TABLE IF EXISTS `tbl_DepartmentMaster`;
CREATE TABLE `tbl_DepartmentMaster` (
  `CUSTOMERCODE` varchar(6) NOT NULL COMMENT '得意先コード',
  `DEPARTMENTID` varchar(4) NOT NULL COMMENT '部門ＩＤ',
  `DEPARTMENTNAME` varchar(40) NOT NULL COMMENT '部門名称',
  `DELETEFLG` char(1) NOT NULL COMMENT '削除フラグ',
  `UPDATERID` varchar(16) NOT NULL COMMENT '更新ユーサーＩＤ',
  `UPDATETIME` DATETIME NOT NULL COMMENT '更新日時',
  PRIMARY KEY (`CUSTOMERCODE`,`DEPARTMENTID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='得意先部門マスター';

DROP TABLE IF EXISTS `tbl_GeneralMaster`;
CREATE TABLE `tbl_GeneralMaster` (
  `KBN` char(2) NOT NULL COMMENT '区分',
  `CODE` varchar(8) NOT NULL COMMENT 'コード',
  `NAME` varchar(50) NOT NULL COMMENT '名称',
  `REMARK` varchar(100) DEFAULT NULL COMMENT '備考',
  `DELETEFLG` char(1) NOT NULL COMMENT '削除フラグ',
  PRIMARY KEY (`KBN`,`CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='汎用マスター';

DROP TABLE IF EXISTS `tbl_CustomerMaster`;
CREATE TABLE `tbl_CustomerMaster` (
  `CUSTOMERCODE` varchar(6) NOT NULL COMMENT '得意先コード',
  `CUSTOMERNAME` varchar(50) NOT NULL COMMENT '得意先名称',
  `CUSTOMERNAMESUM` varchar(5) NOT NULL COMMENT '得意先略称',
  `COMPANYFLG` char(1) NOT NULL COMMENT '会社フラグ',
  `ZIPCODE` varchar(10) NOT NULL COMMENT '郵便番号',
  `ADDRESS` varchar(50) NOT NULL COMMENT '得意先住所',
  `PHONE` varchar(16) NOT NULL COMMENT '得意先電話',
  `FAX` varchar(16) NOT NULL COMMENT '得意先ファックス',
  `COMMENT` varchar(255) NOT NULL COMMENT 'コメント',
  `DELETEFLG` char(1) NOT NULL COMMENT '削除フラグ',
  `UPDATERID` varchar(16) NOT NULL COMMENT '更新ユーサーＩＤ',
  `UPDATETIME` DATETIME NOT NULL COMMENT '更新日時',
  PRIMARY KEY (`CUSTOMERCODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='得意先マスター';

DROP TABLE IF EXISTS `tbl_IDMaster`;
CREATE TABLE `tbl_IDMaster` (
  `PROJECTID` varchar(40) NOT NULL COMMENT 'プロジェクトＩＤ',
  `COMPANYFLG` char(1) NOT NULL COMMENT '社内フラグ',
  `STAGE` char(1) NOT NULL COMMENT '摘出作業',
  `COMPANYNAME` varchar(5) NOT NULL COMMENT '会社名',
  `STAGENAME` varchar(3) NOT NULL COMMENT '作業名',
  `SERIALNO` char(5) NOT NULL COMMENT '連番',
  `UPDATERID` varchar(16) NOT NULL COMMENT '更新ユーサーＩＤ',
  `UPDATETIME` DATETIME NOT NULL COMMENT '更新日時'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='采番マスター';

DROP TABLE IF EXISTS `tbl_ModuleMaster`;
CREATE TABLE `tbl_ModuleMaster` (
  `PROJECTID` varchar(40) NOT NULL COMMENT 'プロジェクトＩＤ',
  `GROUPID` varchar(40) NOT NULL COMMENT 'グループＩＤ',
  `MODULEID` varchar(40) NOT NULL COMMENT 'モジュールＩＤ',
  `MODULENAME` varchar(100) NOT NULL COMMENT 'モジュール名称',
  `DELETEFLG` char(1) NOT NULL COMMENT '削除フラグ',
  `UPDATERID` varchar(16) NOT NULL COMMENT '更新ユーサーＩＤ',
  `UPDATETIME` DATETIME NOT NULL COMMENT '更新日時',
  PRIMARY KEY (`PROJECTID`,`GROUPID`,`MODULEID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='モジュールマスター';

DROP TABLE IF EXISTS `tbl_ProjectMaster`;
CREATE TABLE `tbl_ProjectMaster` (
  `PROJECTID` varchar(40) NOT NULL COMMENT 'プロジェクトＩＤ',
  `PROJECTNAME` varchar(100) NOT NULL COMMENT 'プロジェクト名称',
  `COMPANYINCODE` varchar(6) NOT NULL COMMENT '社内得意先',
  `COMPANOUTCODE` varchar(6) NOT NULL COMMENT '社外得意先',
  `STARTDATE` DATETIME NOT NULL COMMENT '開始日付',
  `ENDDATE` DATETIME NOT NULL COMMENT '終了日付',
  `CHKENDDATE` DATETIME NOT NULL COMMENT '対応終了日付',
  `STATEFLG` char(1) NOT NULL COMMENT '状態フラグ',
  `UPDATERID` varchar(16) NOT NULL COMMENT '更新ユーサーＩＤ',
  `UPDATETIME` DATETIME NOT NULL COMMENT '更新日時',
  `DELETEFLG` char(1) NOT NULL COMMENT '削除フラグ',
  `CHARGEID` VARCHAR(16) NOT NULL COMMENT '責任者',
  PRIMARY KEY (`PROJECTID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='プロジェクトマスター';

DROP TABLE IF EXISTS `tbl_GroupMaster`;
CREATE TABLE `tbl_GroupMaster` (
  `PROJECTID` varchar(40) NOT NULL COMMENT 'プロジェクトＩＤ',
  `GROUPID` varchar(40) NOT NULL COMMENT 'グループＩＤ',
  `GROUPNAME` varchar(100) NOT NULL COMMENT 'グループ名称',
  `DELETEFLG` char(1) NOT NULL COMMENT '削除フラグ',
  `UPDATERID` varchar(16) NOT NULL COMMENT '更新ユーサーＩＤ',
  `UPDATETIME` DATETIME NOT NULL COMMENT '更新日時',
  PRIMARY KEY (`PROJECTID`,`GROUPID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='グループマスター';

DROP TABLE IF EXISTS `tbl_QA`;
CREATE TABLE `tbl_QA` (
  `PROJECTID` varchar(40) NOT NULL COMMENT 'プロジェクトＩＤ',
  `QANO` varchar(11) NOT NULL COMMENT 'Q&A番号',
  `GROUPID` varchar(40) DEFAULT NULL COMMENT 'グループＩＤ',
  `MODULEID` varchar(40) DEFAULT NULL COMMENT 'モジュールＩＤ',
  `COMPANYFLG` char(1) NOT NULL COMMENT '社内フラグ',
  `QAQSTATE` char(1) DEFAULT NULL COMMENT 'Q&A提出方状態',
  `QAASTATE` char(1) DEFAULT NULL COMMENT 'Q&A回答方状態',
  `STAGE` char(1) DEFAULT NULL COMMENT '摘出作業',
  `QUESTIONER` varchar(16) DEFAULT NULL COMMENT '提出者',
  `QUESTIONDATE` DATETIME DEFAULT NULL COMMENT '提出日',
  `EXPDATE` DATETIME DEFAULT NULL COMMENT '希望日',
  `ANSWERER` varchar(16) DEFAULT NULL COMMENT '回答者',
  `ANSWERDATE` DATETIME DEFAULT NULL COMMENT '回答日',
  `QATitle` TEXT(16) DEFAULT NULL COMMENT 'QAタイトル',
  `QATitle_CN` TEXT(16) DEFAULT NULL COMMENT 'QAタイトル（履歴）',
  `QUESTIONINFO` TEXT(16) DEFAULT NULL COMMENT '質問内容',
  `QUESTIONINFO_CN` TEXT(16) DEFAULT NULL COMMENT '質問内容（履歴）',
  `QATTACHEDINFO` varchar(255) DEFAULT NULL COMMENT '質問添付資料',
  `ANSWERINFO` TEXT(16) DEFAULT NULL COMMENT '回答情報',
  `ANSWERINFO_CN` TEXT(16) DEFAULT NULL COMMENT '回答情報（履歴）',
  `AATTACHEDINFO` varchar(255) DEFAULT NULL COMMENT '回答添付資料',
  `TRANSFLG` char(1) DEFAULT NULL COMMENT '翻訳フラグ　',
  `CAUSEDIV` char(2) DEFAULT NULL COMMENT '原因区分',
  `QUESTIONDIV` char(1) DEFAULT NULL COMMENT '質問区分',
  `RELATIONQANO` varchar(11) DEFAULT NULL COMMENT '関係Q&A',
  `REMARK` TEXT(16) DEFAULT NULL COMMENT '備考',
  `REMARK_CN` TEXT(16) DEFAULT NULL COMMENT '備考（履歴）',
  `UPDATERID` varchar(16) NOT NULL COMMENT '更新ユーサーＩＤ',
  `UPDATETIME` DATETIME NOT NULL COMMENT '更新日時',
  PRIMARY KEY (`PROJECTID`,`QANO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Q&A情報';

DROP TABLE IF EXISTS `tbl_ClassMaster`;
CREATE TABLE `tbl_ClassMaster` (
  `CUSTOMERCODE` varchar(6) NOT NULL COMMENT '得意先コード',
  `DEPARTMENTID` varchar(4) NOT NULL COMMENT '部門ＩＤ',
  `CLASSID` varchar(4) NOT NULL COMMENT '課ＩＤ',
  `CLASSNAME` varchar(40) NOT NULL COMMENT '課名称',
  `DELETEFLG` char(1) NOT NULL COMMENT '削除フラグ',
  `UPDATERID` varchar(16) NOT NULL COMMENT '更新ユーサーＩＤ',
  `UPDATETIME` DATETIME NOT NULL COMMENT '更新日時',
  PRIMARY KEY (`CUSTOMERCODE`,`DEPARTMENTID`,`CLASSID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='得意先課マスター ';

DROP TABLE IF EXISTS `tbl_Bug`;
CREATE TABLE `tbl_Bug` (
  `PROJECTID` varchar(40) NOT NULL COMMENT 'プロジェクトＩＤ',
  `BUGNO` varchar(15) NOT NULL COMMENT 'バグ番号',
  `SYSTEMTYPE` varchar(50) DEFAULT NULL COMMENT '機種/OS',
  `GROUPID` varchar(40) DEFAULT NULL COMMENT 'グループＩＤ',
  `MODULEID` varchar(40) DEFAULT NULL COMMENT 'モジュールＩＤ',
  `PRIORFLG` char(1) DEFAULT NULL COMMENT '優先フラグ',
  `COMPANYFLG` char(1) NOT NULL COMMENT '社内フラグ',
  `BUGSTATE` char(1) DEFAULT NULL COMMENT 'バグ状態',
  `OCCURDATE` DATETIME DEFAULT NULL COMMENT '発生日',
  `TESTSPEC` varchar(50) DEFAULT NULL COMMENT 'テスト仕様書(機能名)',
  `STAGE` char(1) DEFAULT NULL COMMENT '摘出作業',
  `PHENOMENON` char(1) DEFAULT NULL COMMENT '現象',
  `BUGTYPE` char(1) DEFAULT NULL COMMENT '障害種別',
  `CONDDIV` char(1) DEFAULT NULL COMMENT '条件区分',
  `DETECTOR` varchar(16) DEFAULT NULL COMMENT '発行者',
  `DEVELOPER` varchar(16) DEFAULT NULL COMMENT '担当者',
  `PLNVERIFIER` varchar(16) DEFAULT NULL COMMENT '予定検証者',
  `VERIFIER` varchar(16) DEFAULT NULL COMMENT '検証者',
  `EXPDATE` DATETIME DEFAULT NULL COMMENT '希望日',
  `BUGINFO` TEXT(16) DEFAULT NULL COMMENT '障害情報',
  `BUGINFO_CN` TEXT(16) DEFAULT NULL COMMENT '障害情報（履歴）',
  `ATTACHEDINFO` varchar(255) DEFAULT NULL COMMENT '添付資料',
  `MODSTARTDATE` DATETIME DEFAULT NULL COMMENT '対応開始日付',
  `MODENDDATE` DATETIME DEFAULT NULL COMMENT '対応終了日付',
  `GENCAUSE` TEXT(16) DEFAULT NULL COMMENT '原因概要',
  `GENCAUSE_CN` TEXT(16) DEFAULT NULL COMMENT '原因概要（履歴）',
  `SOLVEMTD` TEXT(16) DEFAULT NULL COMMENT '処置方法',
  `SOLVEMTD_CN` TEXT(16) DEFAULT NULL COMMENT '処置方法（履歴）',
  `REPLIER` varchar(16) DEFAULT NULL COMMENT '回答者',
  `REPLYDATE` DATETIME DEFAULT NULL COMMENT '回答日',
  `CONFIRMER` varchar(16) DEFAULT NULL COMMENT '確認者',
  `CORRPRONAME` TEXT(16) DEFAULT NULL COMMENT '修正プログラム名',
  `CORRMODNAME` TEXT(16) DEFAULT NULL COMMENT '修正モジュール名',
  `CAUSEDIV` char(1) DEFAULT NULL COMMENT '原因区分',
  `SPECCAUSEDIV` char(1) DEFAULT NULL COMMENT '原因細分',
  `SOLVEDIV` char(1) DEFAULT NULL COMMENT '処置区分',
  `VERIFYDATE` DATETIME DEFAULT NULL COMMENT '検証日',
  `TRANSFLG` char(1) DEFAULT NULL COMMENT '翻訳フラグ　',
  `REMARK` TEXT(16) DEFAULT NULL COMMENT '備考',
  `REMARK_CN` TEXT(16) DEFAULT NULL COMMENT '備考（履歴）',
  `UPDATERID` varchar(16) NOT NULL COMMENT '更新ユーサーＩＤ',
  `UPDATETIME` DATETIME NOT NULL COMMENT '更新日時',
  PRIMARY KEY (`PROJECTID`,`BUGNO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='バグ情報';

DROP TABLE IF EXISTS `tbl_QAHistory`;
CREATE TABLE `tbl_QAHistory` (
  `PROJECTID` varchar(40) NOT NULL COMMENT 'プロジェクトＩＤ',
  `QANO` varchar(11) NOT NULL COMMENT 'Q&A番号',
  `SERIALNUM` varchar(5) NOT NULL COMMENT '連番',
  `GROUPID` varchar(40) DEFAULT NULL COMMENT 'グループＩＤ',
  `MODULEID` varchar(40) DEFAULT NULL COMMENT 'モジュールＩＤ',
  `COMPANYFLG` char(1) NOT NULL COMMENT '社内フラグ',
  `QAQSTATE` char(1) DEFAULT NULL COMMENT 'Q&A提出方状態',
  `QAASTATE` char(1) DEFAULT NULL COMMENT 'Q&A回答方状態',
  `STAGE` char(1) DEFAULT NULL COMMENT '摘出作業',
  `QUESTIONER` varchar(16) DEFAULT NULL COMMENT '提出者',
  `QUESTIONDATE` DATETIME DEFAULT NULL COMMENT '提出日',
  `EXPDATE` DATETIME DEFAULT NULL COMMENT '希望日',
  `ANSWERER` varchar(16) DEFAULT NULL COMMENT '回答者',
  `ANSWERDATE` DATETIME DEFAULT NULL COMMENT '回答日',
  `QATitle` TEXT(16) DEFAULT NULL COMMENT 'QAタイトル',
  `QATitle_CN` TEXT(16) DEFAULT NULL COMMENT 'QAタイトル（履歴）',
  `QUESTIONINFO` TEXT(16) DEFAULT NULL COMMENT '質問内容',
  `QUESTIONINFO_CN` TEXT(16) DEFAULT NULL COMMENT '質問内容（履歴）',
  `QATTACHEDINFO` varchar(255) DEFAULT NULL COMMENT '質問添付資料',
  `ANSWERINFO` TEXT(16) DEFAULT NULL COMMENT '回答情報',
  `ANSWERINFO_CN` TEXT(16) DEFAULT NULL COMMENT '回答情報（履歴）',
  `AATTACHEDINFO` varchar(255) DEFAULT NULL COMMENT '回答添付資料',
  `TRANSFLG` char(1) DEFAULT NULL COMMENT '翻訳フラグ　',
  `CAUSEDIV` char(2) DEFAULT NULL COMMENT '原因区分',
  `QUESTIONDIV` char(1) DEFAULT NULL COMMENT '質問区分',
  `RELATIONQANO` varchar(11) DEFAULT NULL COMMENT '関係Q&A',
  `REMARK` TEXT(16) DEFAULT NULL COMMENT '備考',
  `REMARK_CN` TEXT(16) DEFAULT NULL COMMENT '備考（履歴）',
  `UPDATERID` varchar(16) NOT NULL COMMENT '更新ユーサーＩＤ',
  `UPDATETIME` DATETIME NOT NULL COMMENT '更新日時',
  PRIMARY KEY (`PROJECTID`,`QANO`,`SERIALNUM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Q&A情報履歴';

DROP TABLE IF EXISTS `tbl_QAIDMaster`;
CREATE TABLE `tbl_QAIDMaster` (
  `PROJECTID` varchar(40) NOT NULL COMMENT 'プロジェクトＩＤ',
  `COMPANYNAME` varchar(5) NOT NULL COMMENT '会社名',
  `SERIALNO` char(5) NOT NULL COMMENT '連番',
  `UPDATERID` varchar(16) NOT NULL COMMENT '更新ユーサーＩＤ',
  `UPDATETIME` DATETIME NOT NULL COMMENT '更新日時'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='QA采番マスター';

DROP TABLE IF EXISTS `tbl_ProjectMemberMaster`;
CREATE TABLE `tbl_ProjectMemberMaster` (
  `PROJECTID` varchar(40) NOT NULL COMMENT 'プロジェクトＩＤ',
  `USERID` varchar(16) NOT NULL COMMENT 'ユーサーＩＤ',
  `WORKTYPE` char(1) NOT NULL COMMENT '担当ＩＤ',
  `UPDATERID` varchar(16) NOT NULL COMMENT '更新ユーサーＩＤ',
  `UPDATETIME` DATETIME NOT NULL COMMENT '更新日時',
  PRIMARY KEY (`PROJECTID`,`USERID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='メンバーマスター';

DROP TABLE IF EXISTS `tbl_BugHistory`;
CREATE TABLE `tbl_BugHistory` (
  `PROJECTID` varchar(40) NOT NULL COMMENT 'プロジェクトＩＤ',
  `BUGNO` varchar(15) NOT NULL COMMENT 'バグ番号',
  `SERIALNUM` varchar(5) NOT NULL COMMENT '連番',
  `SYSTEMTYPE` varchar(50) DEFAULT NULL COMMENT '機種/OS',
  `GROUPID` varchar(40) DEFAULT NULL COMMENT 'グループＩＤ',
  `MODULEID` varchar(40) DEFAULT NULL COMMENT 'モジュールＩＤ',
  `PRIORFLG` char(1) DEFAULT NULL COMMENT '優先フラグ',
  `COMPANYFLG` char(1) NOT NULL COMMENT '社内フラグ',
  `BUGSTATE` char(1) DEFAULT NULL COMMENT 'バグ状態',
  `OCCURDATE` DATETIME DEFAULT NULL COMMENT '発生日',
  `TESTSPEC` varchar(50) DEFAULT NULL COMMENT 'テスト仕様書(機能名)',
  `STAGE` char(1) DEFAULT NULL COMMENT '摘出作業',
  `PHENOMENON` char(1) DEFAULT NULL COMMENT '現象',
  `BUGTYPE` char(1) DEFAULT NULL COMMENT '障害種別',
  `CONDDIV` char(1) DEFAULT NULL COMMENT '条件区分',
  `DETECTOR` varchar(16) DEFAULT NULL COMMENT '発行者',
  `DEVELOPER` varchar(16) DEFAULT NULL COMMENT '担当者',
  `VERIFIER` varchar(16) DEFAULT NULL COMMENT '検証者',
  `PLNVERIFIER` varchar(16) DEFAULT NULL COMMENT '予定検証者',
  `EXPDATE` DATETIME DEFAULT NULL COMMENT '希望日',
  `BUGINFO` TEXT(16) DEFAULT NULL COMMENT '障害情報',
  `BUGINFO_CN` TEXT(16) DEFAULT NULL COMMENT '障害情報（履歴）',
  `ATTACHEDINFO` varchar(255) DEFAULT NULL COMMENT '添付資料',
  `PLNSTARTDATE` DATETIME DEFAULT NULL COMMENT '対応開始日付',
  `PLNENDDATE` DATETIME DEFAULT NULL COMMENT '対応終了日付',
  `GENCAUSE` TEXT(16) DEFAULT NULL COMMENT '原因概要',
  `GENCAUSE_CN` TEXT(16) DEFAULT NULL COMMENT '原因概要（履歴）',
  `SOLVEMTD` TEXT(16) DEFAULT NULL COMMENT '処置方法',
  `SOLVEMTD_CN` TEXT(16) DEFAULT NULL COMMENT '処置方法（履歴）',
  `REPLIER` varchar(16) DEFAULT NULL COMMENT '回答者',
  `REPLYDATE` DATETIME DEFAULT NULL COMMENT '回答日',
  `CONFIRMER` varchar(16) DEFAULT NULL COMMENT '確認者',
  `CORRPRONAME` TEXT(16) DEFAULT NULL COMMENT '修正プログラム名',
  `CORRMODNAME` TEXT(16) DEFAULT NULL COMMENT '修正モジュール名',
  `CAUSEDIV` char(1) DEFAULT NULL COMMENT '原因区分',
  `SPECCAUSEDIV` char(1) DEFAULT NULL COMMENT '原因細分',
  `SOLVEDIV` char(1) DEFAULT NULL COMMENT '処置区分',
  `VERIFYDATE` DATETIME DEFAULT NULL COMMENT '検証日',
  `TRANSFLG` char(1) DEFAULT NULL COMMENT '翻訳フラグ　',
  `REMARK` TEXT(16) DEFAULT NULL COMMENT '備考',
  `REMARK_CN` TEXT(16) DEFAULT NULL COMMENT '備考（履歴）',
  `UPDATERID` varchar(16) NOT NULL COMMENT '更新ユーサーＩＤ',
  `UPDATETIME` DATETIME NOT NULL COMMENT '更新日時',
  PRIMARY KEY (`PROJECTID`,`BUGNO`,`SERIALNUM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='バグ情報履歴';
